"""Contains a dict with locations and their Stn Codes"""

LOCATION = {
    38: "Kathivakkam, Chennai",
    71: "Manali, Chennai",
    72: "Thiruvottiyur, Chennai",
    159: "Madras Medical College, Chennai",
    160: "NEERI CSIR Campus, Chennai",
    161: "Thiruvottiyur Municipal Office, Chennai",
    237: "SIDCO Office, Coimbatore",
    238: "Dist. Collector's Office, Coimbatore",
    239: "Fisheries College, Tuticorin",
    240: " Raja Agencies, Tuticorin",
    306: "Highways Project Building, Madurai",
    307: "Fenner, Madurai",
    308: "Kunnathur Chatram East Avani Mollai Street, Madurai",
    309: "Sowdeswari College Building, Salem",
    366: "AVM Jewellery Building, Tuticorin",
    375: "Poniarajapuram, Coimbatore",
    760: "SIPCOT Industrial Complex, Cuddalore",
    761: "DEE Office",
    762: "Raman Nagar, Mettur",
    763: "SIDCO Industrial Complex, Mettur",
    764: "Adyar, Chennai",
    765: "Anna Nagar, Chennai",
    766: "Thiyagaraya Nagar, Chennai",
    767: "Kilpauk, Chennai",
    768: "Vallalar Nagar, Chennai",
    769: "Gandhi Market, Trichy",
    770: "Main Guard Gate, Trichy",
    771: "Bishop Heber College, Trichy",
    772: "Golden Rock, Trichy",
    773: "Central Bus Stand, Trichy"
}
